---
# Build information from the inspected instance
# This information should not come from accessing the instance directly.
   # ######################################################################## #
   # Copyright 2020 Amazon Web Services, Inc.                                 #
   #                                                                          #
   # Licensed under the Apache License, Version 2.0 (the "License");          #
   # you may not use this file except in compliance with the License.         #
   # You may obtain a copy of the License at                                  #
   #                                                                          #
   #     http://www.apache.org/licenses/LICENSE-2.0                           #
   #                                                                          #
   # Unless required by applicable law or agreed to in writing, software      #
   # distributed under the License is distributed on an "AS IS" BASIS,        #
   # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
   # See the License for the specific language governing permissions and      #
   # limitations under the License.                                           #
   # ######################################################################## #

- name: RHEL-6-INSTANCE | Gather information from RHEL6 instance
  community.aws.ec2_instance_info:
    aws_access_key: "{{ inject.aws_access_key | default(omit) }}"
    aws_secret_key: "{{ inject.aws_secret_key | default(omit) }}"
    profile: "{{ inject.profile | default(omit) }}"
    region: "{{ inject.region | default(omit) }}"
    filters:
      dns-name: "{{ inventory_hostname }}"
  register: donor_instances_info
  delegate_to: 127.0.0.1

- name: VPC | Gather the details related to the instance
  ansible.builtin.set_fact:
    donor_instance_az: "{{ donor_instances_info.instances[0].placement.availability_zone }}"
    donor_instance_key: "{{ donor_instances_info.instances[0].key_name }}"
    donor_instance_ip_address: "{{ donor_instances_info.instances[0].private_ip_address }}"
    donor_instance_subnet_id: "{{ donor_instances_info.instances[0].subnet_id }}"
    donor_instance_security_groups: "{{ donor_instances_info.instances[0].security_groups }}"
    donor_instance_tags: "{{ donor_instances_info.instances[0].tags }}"
    donor_instance_id: "{{ donor_instances_info.instances[0].instance_id }}"
    donor_instance_type: "{{ donor_instances_info.instances[0].instance_type }}"
    donor_instance_block_device_mappings: >-
      {{ donor_instances_info.instances[0].block_device_mappings }}
    donor_instance_root_volume_id: >-
        {{ donor_instances_info.instances[0].block_device_mappings | community.general.json_query('[?device_name == `/dev/sda1`].ebs.volume_id | [-1]') }}
    donor_instance_root_volume_device_name: >-
        {{ donor_instances_info.instances[0].block_device_mappings | community.general.json_query('[?device_name == `/dev/sda1`].device_name | [-1]') }}
