---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: rhel-6-els-tester
    vpc_subnet_id: subnet-08b65873
    profile: ansible
    region: us-east-1
provisioner:
  name: ansible
verifier:
  name: ansible
